language: php
cache: false

sudo: false

php:
  - 5.6
  - 7.2

before_script:
  - COMPOSER_MEMORY_LIMIT=-1 travis_retry composer install

script:
  - composer test-ci
  - composer cs
  - composer phpstan

after_script:
  - sh .travis.coverage.sh
